// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvqzlvwuogimtfxqvnxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2cXpsdnd1b2dpbXRmeHF2bnhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyOTkwNTksImV4cCI6MjA2OTg3NTA1OX0.KgfKd58IhKZgmwZKfmFEgt5vb1JpgNzQOBkSckWb4Z0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});